package com.yangmao.dal.dataobj;

import java.util.Date;

public class YangmaoEmailSender {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_email_sender.sender_id
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    private Long senderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_email_sender.name
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_email_sender.email
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_email_sender.password
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_email_sender.host
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    private String host;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_email_sender.status
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_email_sender.effecttive_date
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    private Date effecttiveDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_email_sender.sender_id
     *
     * @return the value of yangmao_email_sender.sender_id
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public Long getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_email_sender.sender_id
     *
     * @param senderId the value for yangmao_email_sender.sender_id
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public void setSenderId(Long senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_email_sender.name
     *
     * @return the value of yangmao_email_sender.name
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_email_sender.name
     *
     * @param name the value for yangmao_email_sender.name
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_email_sender.email
     *
     * @return the value of yangmao_email_sender.email
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_email_sender.email
     *
     * @param email the value for yangmao_email_sender.email
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_email_sender.password
     *
     * @return the value of yangmao_email_sender.password
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_email_sender.password
     *
     * @param password the value for yangmao_email_sender.password
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_email_sender.host
     *
     * @return the value of yangmao_email_sender.host
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_email_sender.host
     *
     * @param host the value for yangmao_email_sender.host
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_email_sender.status
     *
     * @return the value of yangmao_email_sender.status
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_email_sender.status
     *
     * @param status the value for yangmao_email_sender.status
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_email_sender.effecttive_date
     *
     * @return the value of yangmao_email_sender.effecttive_date
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public Date getEffecttiveDate() {
        return effecttiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_email_sender.effecttive_date
     *
     * @param effecttiveDate the value for yangmao_email_sender.effecttive_date
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public void setEffecttiveDate(Date effecttiveDate) {
        this.effecttiveDate = effecttiveDate;
    }
}