package com.yangmao.dal.dataobj;

public class YangmaoMailInstanceItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_mail_instance_item.instance_item_id
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    private Long instanceItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_mail_instance_item.mail_instance_id
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    private Long mailInstanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_mail_instance_item.item_id
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_mail_instance_item.section
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    private String section;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_mail_instance_item.instance_item_id
     *
     * @return the value of yangmao_mail_instance_item.instance_item_id
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public Long getInstanceItemId() {
        return instanceItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_mail_instance_item.instance_item_id
     *
     * @param instanceItemId the value for yangmao_mail_instance_item.instance_item_id
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public void setInstanceItemId(Long instanceItemId) {
        this.instanceItemId = instanceItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_mail_instance_item.mail_instance_id
     *
     * @return the value of yangmao_mail_instance_item.mail_instance_id
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public Long getMailInstanceId() {
        return mailInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_mail_instance_item.mail_instance_id
     *
     * @param mailInstanceId the value for yangmao_mail_instance_item.mail_instance_id
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public void setMailInstanceId(Long mailInstanceId) {
        this.mailInstanceId = mailInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_mail_instance_item.item_id
     *
     * @return the value of yangmao_mail_instance_item.item_id
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_mail_instance_item.item_id
     *
     * @param itemId the value for yangmao_mail_instance_item.item_id
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_mail_instance_item.section
     *
     * @return the value of yangmao_mail_instance_item.section
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public String getSection() {
        return section;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_mail_instance_item.section
     *
     * @param section the value for yangmao_mail_instance_item.section
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public void setSection(String section) {
        this.section = section == null ? null : section.trim();
    }
}