package com.yangmao.dal.dataobj;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class YangmaoClickExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yangmao_click
     *
     * @mbggenerated Thu Aug 25 15:46:14 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yangmao_click
     *
     * @mbggenerated Thu Aug 25 15:46:14 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yangmao_click
     *
     * @mbggenerated Thu Aug 25 15:46:14 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Thu Aug 25 15:46:14 CST 2016
     */
    public YangmaoClickExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Thu Aug 25 15:46:14 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Thu Aug 25 15:46:14 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Thu Aug 25 15:46:14 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Thu Aug 25 15:46:14 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Thu Aug 25 15:46:14 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Thu Aug 25 15:46:14 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Thu Aug 25 15:46:14 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Thu Aug 25 15:46:14 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Thu Aug 25 15:46:14 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Thu Aug 25 15:46:14 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yangmao_click
     *
     * @mbggenerated Thu Aug 25 15:46:14 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andClickIdIsNull() {
            addCriterion("click_id is null");
            return (Criteria) this;
        }

        public Criteria andClickIdIsNotNull() {
            addCriterion("click_id is not null");
            return (Criteria) this;
        }

        public Criteria andClickIdEqualTo(Long value) {
            addCriterion("click_id =", value, "clickId");
            return (Criteria) this;
        }

        public Criteria andClickIdNotEqualTo(Long value) {
            addCriterion("click_id <>", value, "clickId");
            return (Criteria) this;
        }

        public Criteria andClickIdGreaterThan(Long value) {
            addCriterion("click_id >", value, "clickId");
            return (Criteria) this;
        }

        public Criteria andClickIdGreaterThanOrEqualTo(Long value) {
            addCriterion("click_id >=", value, "clickId");
            return (Criteria) this;
        }

        public Criteria andClickIdLessThan(Long value) {
            addCriterion("click_id <", value, "clickId");
            return (Criteria) this;
        }

        public Criteria andClickIdLessThanOrEqualTo(Long value) {
            addCriterion("click_id <=", value, "clickId");
            return (Criteria) this;
        }

        public Criteria andClickIdIn(List<Long> values) {
            addCriterion("click_id in", values, "clickId");
            return (Criteria) this;
        }

        public Criteria andClickIdNotIn(List<Long> values) {
            addCriterion("click_id not in", values, "clickId");
            return (Criteria) this;
        }

        public Criteria andClickIdBetween(Long value1, Long value2) {
            addCriterion("click_id between", value1, value2, "clickId");
            return (Criteria) this;
        }

        public Criteria andClickIdNotBetween(Long value1, Long value2) {
            addCriterion("click_id not between", value1, value2, "clickId");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andMailInstanceIdIsNull() {
            addCriterion("mail_instance_id is null");
            return (Criteria) this;
        }

        public Criteria andMailInstanceIdIsNotNull() {
            addCriterion("mail_instance_id is not null");
            return (Criteria) this;
        }

        public Criteria andMailInstanceIdEqualTo(Long value) {
            addCriterion("mail_instance_id =", value, "mailInstanceId");
            return (Criteria) this;
        }

        public Criteria andMailInstanceIdNotEqualTo(Long value) {
            addCriterion("mail_instance_id <>", value, "mailInstanceId");
            return (Criteria) this;
        }

        public Criteria andMailInstanceIdGreaterThan(Long value) {
            addCriterion("mail_instance_id >", value, "mailInstanceId");
            return (Criteria) this;
        }

        public Criteria andMailInstanceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("mail_instance_id >=", value, "mailInstanceId");
            return (Criteria) this;
        }

        public Criteria andMailInstanceIdLessThan(Long value) {
            addCriterion("mail_instance_id <", value, "mailInstanceId");
            return (Criteria) this;
        }

        public Criteria andMailInstanceIdLessThanOrEqualTo(Long value) {
            addCriterion("mail_instance_id <=", value, "mailInstanceId");
            return (Criteria) this;
        }

        public Criteria andMailInstanceIdIn(List<Long> values) {
            addCriterion("mail_instance_id in", values, "mailInstanceId");
            return (Criteria) this;
        }

        public Criteria andMailInstanceIdNotIn(List<Long> values) {
            addCriterion("mail_instance_id not in", values, "mailInstanceId");
            return (Criteria) this;
        }

        public Criteria andMailInstanceIdBetween(Long value1, Long value2) {
            addCriterion("mail_instance_id between", value1, value2, "mailInstanceId");
            return (Criteria) this;
        }

        public Criteria andMailInstanceIdNotBetween(Long value1, Long value2) {
            addCriterion("mail_instance_id not between", value1, value2, "mailInstanceId");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNull() {
            addCriterion("item_id is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("item_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(Long value) {
            addCriterion("item_id =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(Long value) {
            addCriterion("item_id <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(Long value) {
            addCriterion("item_id >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(Long value) {
            addCriterion("item_id >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(Long value) {
            addCriterion("item_id <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(Long value) {
            addCriterion("item_id <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<Long> values) {
            addCriterion("item_id in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<Long> values) {
            addCriterion("item_id not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(Long value1, Long value2) {
            addCriterion("item_id between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(Long value1, Long value2) {
            addCriterion("item_id not between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yangmao_click
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 25 15:46:14 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yangmao_click
     *
     * @mbggenerated Thu Aug 25 15:46:14 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}