package com.yangmao.dal.dataobj;

import java.util.Date;

public class YangmaoMailTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_mail_template.template_id
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private Long templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_mail_template.name
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_mail_template.title
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_mail_template.status
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_mail_template.create_time
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_mail_template.last_update_time
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_mail_template.content
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_mail_template.template_id
     *
     * @return the value of yangmao_mail_template.template_id
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public Long getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_mail_template.template_id
     *
     * @param templateId the value for yangmao_mail_template.template_id
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_mail_template.name
     *
     * @return the value of yangmao_mail_template.name
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_mail_template.name
     *
     * @param name the value for yangmao_mail_template.name
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_mail_template.title
     *
     * @return the value of yangmao_mail_template.title
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_mail_template.title
     *
     * @param title the value for yangmao_mail_template.title
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_mail_template.status
     *
     * @return the value of yangmao_mail_template.status
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_mail_template.status
     *
     * @param status the value for yangmao_mail_template.status
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_mail_template.create_time
     *
     * @return the value of yangmao_mail_template.create_time
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_mail_template.create_time
     *
     * @param createTime the value for yangmao_mail_template.create_time
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_mail_template.last_update_time
     *
     * @return the value of yangmao_mail_template.last_update_time
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_mail_template.last_update_time
     *
     * @param lastUpdateTime the value for yangmao_mail_template.last_update_time
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_mail_template.content
     *
     * @return the value of yangmao_mail_template.content
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_mail_template.content
     *
     * @param content the value for yangmao_mail_template.content
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}