package com.yangmao.dal.dataobj;

import java.math.BigDecimal;
import java.util.Date;

public class YangmaoFavoritesItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_favorites_item.item_id
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_favorites_item.num_iid
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private Long numIid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_favorites_item.yangmao_favorites_id
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private Long yangmaoFavoritesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_favorites_item.title
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_favorites_item.item_url
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private String itemUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_favorites_item.pict_url
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private String pictUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_favorites_item.item_images
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private String itemImages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_favorites_item.nick
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private String nick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_favorites_item.seller_id
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private Long sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_favorites_item.shop_title
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private String shopTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_favorites_item.provcity
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private String provcity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_favorites_item.original_price
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private BigDecimal originalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_favorites_item.final_price
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private BigDecimal finalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_favorites_item.final_price_wap
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private BigDecimal finalPriceWap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_favorites_item.click_url
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private String clickUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_favorites_item.tk_rate
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private BigDecimal tkRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_favorites_item.volume
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private Integer volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_favorites_item.create_time
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_favorites_item.last_update_time
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_favorites_item.item_id
     *
     * @return the value of yangmao_favorites_item.item_id
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_favorites_item.item_id
     *
     * @param itemId the value for yangmao_favorites_item.item_id
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_favorites_item.num_iid
     *
     * @return the value of yangmao_favorites_item.num_iid
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public Long getNumIid() {
        return numIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_favorites_item.num_iid
     *
     * @param numIid the value for yangmao_favorites_item.num_iid
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setNumIid(Long numIid) {
        this.numIid = numIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_favorites_item.yangmao_favorites_id
     *
     * @return the value of yangmao_favorites_item.yangmao_favorites_id
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public Long getYangmaoFavoritesId() {
        return yangmaoFavoritesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_favorites_item.yangmao_favorites_id
     *
     * @param yangmaoFavoritesId the value for yangmao_favorites_item.yangmao_favorites_id
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setYangmaoFavoritesId(Long yangmaoFavoritesId) {
        this.yangmaoFavoritesId = yangmaoFavoritesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_favorites_item.title
     *
     * @return the value of yangmao_favorites_item.title
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_favorites_item.title
     *
     * @param title the value for yangmao_favorites_item.title
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_favorites_item.item_url
     *
     * @return the value of yangmao_favorites_item.item_url
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public String getItemUrl() {
        return itemUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_favorites_item.item_url
     *
     * @param itemUrl the value for yangmao_favorites_item.item_url
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setItemUrl(String itemUrl) {
        this.itemUrl = itemUrl == null ? null : itemUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_favorites_item.pict_url
     *
     * @return the value of yangmao_favorites_item.pict_url
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public String getPictUrl() {
        return pictUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_favorites_item.pict_url
     *
     * @param pictUrl the value for yangmao_favorites_item.pict_url
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setPictUrl(String pictUrl) {
        this.pictUrl = pictUrl == null ? null : pictUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_favorites_item.item_images
     *
     * @return the value of yangmao_favorites_item.item_images
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public String getItemImages() {
        return itemImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_favorites_item.item_images
     *
     * @param itemImages the value for yangmao_favorites_item.item_images
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setItemImages(String itemImages) {
        this.itemImages = itemImages == null ? null : itemImages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_favorites_item.nick
     *
     * @return the value of yangmao_favorites_item.nick
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_favorites_item.nick
     *
     * @param nick the value for yangmao_favorites_item.nick
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setNick(String nick) {
        this.nick = nick == null ? null : nick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_favorites_item.seller_id
     *
     * @return the value of yangmao_favorites_item.seller_id
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_favorites_item.seller_id
     *
     * @param sellerId the value for yangmao_favorites_item.seller_id
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_favorites_item.shop_title
     *
     * @return the value of yangmao_favorites_item.shop_title
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public String getShopTitle() {
        return shopTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_favorites_item.shop_title
     *
     * @param shopTitle the value for yangmao_favorites_item.shop_title
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setShopTitle(String shopTitle) {
        this.shopTitle = shopTitle == null ? null : shopTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_favorites_item.provcity
     *
     * @return the value of yangmao_favorites_item.provcity
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public String getProvcity() {
        return provcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_favorites_item.provcity
     *
     * @param provcity the value for yangmao_favorites_item.provcity
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setProvcity(String provcity) {
        this.provcity = provcity == null ? null : provcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_favorites_item.original_price
     *
     * @return the value of yangmao_favorites_item.original_price
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public BigDecimal getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_favorites_item.original_price
     *
     * @param originalPrice the value for yangmao_favorites_item.original_price
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setOriginalPrice(BigDecimal originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_favorites_item.final_price
     *
     * @return the value of yangmao_favorites_item.final_price
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public BigDecimal getFinalPrice() {
        return finalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_favorites_item.final_price
     *
     * @param finalPrice the value for yangmao_favorites_item.final_price
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setFinalPrice(BigDecimal finalPrice) {
        this.finalPrice = finalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_favorites_item.final_price_wap
     *
     * @return the value of yangmao_favorites_item.final_price_wap
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public BigDecimal getFinalPriceWap() {
        return finalPriceWap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_favorites_item.final_price_wap
     *
     * @param finalPriceWap the value for yangmao_favorites_item.final_price_wap
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setFinalPriceWap(BigDecimal finalPriceWap) {
        this.finalPriceWap = finalPriceWap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_favorites_item.click_url
     *
     * @return the value of yangmao_favorites_item.click_url
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public String getClickUrl() {
        return clickUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_favorites_item.click_url
     *
     * @param clickUrl the value for yangmao_favorites_item.click_url
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setClickUrl(String clickUrl) {
        this.clickUrl = clickUrl == null ? null : clickUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_favorites_item.tk_rate
     *
     * @return the value of yangmao_favorites_item.tk_rate
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public BigDecimal getTkRate() {
        return tkRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_favorites_item.tk_rate
     *
     * @param tkRate the value for yangmao_favorites_item.tk_rate
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setTkRate(BigDecimal tkRate) {
        this.tkRate = tkRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_favorites_item.volume
     *
     * @return the value of yangmao_favorites_item.volume
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public Integer getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_favorites_item.volume
     *
     * @param volume the value for yangmao_favorites_item.volume
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setVolume(Integer volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_favorites_item.create_time
     *
     * @return the value of yangmao_favorites_item.create_time
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_favorites_item.create_time
     *
     * @param createTime the value for yangmao_favorites_item.create_time
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_favorites_item.last_update_time
     *
     * @return the value of yangmao_favorites_item.last_update_time
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_favorites_item.last_update_time
     *
     * @param lastUpdateTime the value for yangmao_favorites_item.last_update_time
     *
     * @mbggenerated Mon Aug 29 14:35:12 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}