package com.yangmao.dal.dataobj;

import java.util.Date;

public class YangmaoReplaceField {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_replace_field.replace_field_id
     *
     * @mbggenerated Sun Sep 04 23:10:26 CST 2016
     */
    private Long replaceFieldId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_replace_field.template_replace_name
     *
     * @mbggenerated Sun Sep 04 23:10:26 CST 2016
     */
    private String templateReplaceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_replace_field.database_field
     *
     * @mbggenerated Sun Sep 04 23:10:26 CST 2016
     */
    private String databaseField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_replace_field.level
     *
     * @mbggenerated Sun Sep 04 23:10:26 CST 2016
     */
    private Byte level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_replace_field.create_time
     *
     * @mbggenerated Sun Sep 04 23:10:26 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_replace_field.last_update_time
     *
     * @mbggenerated Sun Sep 04 23:10:26 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_replace_field.replace_field_id
     *
     * @return the value of yangmao_replace_field.replace_field_id
     *
     * @mbggenerated Sun Sep 04 23:10:26 CST 2016
     */
    public Long getReplaceFieldId() {
        return replaceFieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_replace_field.replace_field_id
     *
     * @param replaceFieldId the value for yangmao_replace_field.replace_field_id
     *
     * @mbggenerated Sun Sep 04 23:10:26 CST 2016
     */
    public void setReplaceFieldId(Long replaceFieldId) {
        this.replaceFieldId = replaceFieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_replace_field.template_replace_name
     *
     * @return the value of yangmao_replace_field.template_replace_name
     *
     * @mbggenerated Sun Sep 04 23:10:26 CST 2016
     */
    public String getTemplateReplaceName() {
        return templateReplaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_replace_field.template_replace_name
     *
     * @param templateReplaceName the value for yangmao_replace_field.template_replace_name
     *
     * @mbggenerated Sun Sep 04 23:10:26 CST 2016
     */
    public void setTemplateReplaceName(String templateReplaceName) {
        this.templateReplaceName = templateReplaceName == null ? null : templateReplaceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_replace_field.database_field
     *
     * @return the value of yangmao_replace_field.database_field
     *
     * @mbggenerated Sun Sep 04 23:10:26 CST 2016
     */
    public String getDatabaseField() {
        return databaseField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_replace_field.database_field
     *
     * @param databaseField the value for yangmao_replace_field.database_field
     *
     * @mbggenerated Sun Sep 04 23:10:26 CST 2016
     */
    public void setDatabaseField(String databaseField) {
        this.databaseField = databaseField == null ? null : databaseField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_replace_field.level
     *
     * @return the value of yangmao_replace_field.level
     *
     * @mbggenerated Sun Sep 04 23:10:26 CST 2016
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_replace_field.level
     *
     * @param level the value for yangmao_replace_field.level
     *
     * @mbggenerated Sun Sep 04 23:10:26 CST 2016
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_replace_field.create_time
     *
     * @return the value of yangmao_replace_field.create_time
     *
     * @mbggenerated Sun Sep 04 23:10:26 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_replace_field.create_time
     *
     * @param createTime the value for yangmao_replace_field.create_time
     *
     * @mbggenerated Sun Sep 04 23:10:26 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_replace_field.last_update_time
     *
     * @return the value of yangmao_replace_field.last_update_time
     *
     * @mbggenerated Sun Sep 04 23:10:26 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_replace_field.last_update_time
     *
     * @param lastUpdateTime the value for yangmao_replace_field.last_update_time
     *
     * @mbggenerated Sun Sep 04 23:10:26 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}