package com.yangmao.dal.dataobj;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class YangmaoFavoritesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yangmao_favorites
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yangmao_favorites
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yangmao_favorites
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public YangmaoFavoritesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yangmao_favorites
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andYangmaoFavoritesIdIsNull() {
            addCriterion("yangmao_favorites_id is null");
            return (Criteria) this;
        }

        public Criteria andYangmaoFavoritesIdIsNotNull() {
            addCriterion("yangmao_favorites_id is not null");
            return (Criteria) this;
        }

        public Criteria andYangmaoFavoritesIdEqualTo(Long value) {
            addCriterion("yangmao_favorites_id =", value, "yangmaoFavoritesId");
            return (Criteria) this;
        }

        public Criteria andYangmaoFavoritesIdNotEqualTo(Long value) {
            addCriterion("yangmao_favorites_id <>", value, "yangmaoFavoritesId");
            return (Criteria) this;
        }

        public Criteria andYangmaoFavoritesIdGreaterThan(Long value) {
            addCriterion("yangmao_favorites_id >", value, "yangmaoFavoritesId");
            return (Criteria) this;
        }

        public Criteria andYangmaoFavoritesIdGreaterThanOrEqualTo(Long value) {
            addCriterion("yangmao_favorites_id >=", value, "yangmaoFavoritesId");
            return (Criteria) this;
        }

        public Criteria andYangmaoFavoritesIdLessThan(Long value) {
            addCriterion("yangmao_favorites_id <", value, "yangmaoFavoritesId");
            return (Criteria) this;
        }

        public Criteria andYangmaoFavoritesIdLessThanOrEqualTo(Long value) {
            addCriterion("yangmao_favorites_id <=", value, "yangmaoFavoritesId");
            return (Criteria) this;
        }

        public Criteria andYangmaoFavoritesIdIn(List<Long> values) {
            addCriterion("yangmao_favorites_id in", values, "yangmaoFavoritesId");
            return (Criteria) this;
        }

        public Criteria andYangmaoFavoritesIdNotIn(List<Long> values) {
            addCriterion("yangmao_favorites_id not in", values, "yangmaoFavoritesId");
            return (Criteria) this;
        }

        public Criteria andYangmaoFavoritesIdBetween(Long value1, Long value2) {
            addCriterion("yangmao_favorites_id between", value1, value2, "yangmaoFavoritesId");
            return (Criteria) this;
        }

        public Criteria andYangmaoFavoritesIdNotBetween(Long value1, Long value2) {
            addCriterion("yangmao_favorites_id not between", value1, value2, "yangmaoFavoritesId");
            return (Criteria) this;
        }

        public Criteria andFavoritesIdIsNull() {
            addCriterion("favorites_id is null");
            return (Criteria) this;
        }

        public Criteria andFavoritesIdIsNotNull() {
            addCriterion("favorites_id is not null");
            return (Criteria) this;
        }

        public Criteria andFavoritesIdEqualTo(Long value) {
            addCriterion("favorites_id =", value, "favoritesId");
            return (Criteria) this;
        }

        public Criteria andFavoritesIdNotEqualTo(Long value) {
            addCriterion("favorites_id <>", value, "favoritesId");
            return (Criteria) this;
        }

        public Criteria andFavoritesIdGreaterThan(Long value) {
            addCriterion("favorites_id >", value, "favoritesId");
            return (Criteria) this;
        }

        public Criteria andFavoritesIdGreaterThanOrEqualTo(Long value) {
            addCriterion("favorites_id >=", value, "favoritesId");
            return (Criteria) this;
        }

        public Criteria andFavoritesIdLessThan(Long value) {
            addCriterion("favorites_id <", value, "favoritesId");
            return (Criteria) this;
        }

        public Criteria andFavoritesIdLessThanOrEqualTo(Long value) {
            addCriterion("favorites_id <=", value, "favoritesId");
            return (Criteria) this;
        }

        public Criteria andFavoritesIdIn(List<Long> values) {
            addCriterion("favorites_id in", values, "favoritesId");
            return (Criteria) this;
        }

        public Criteria andFavoritesIdNotIn(List<Long> values) {
            addCriterion("favorites_id not in", values, "favoritesId");
            return (Criteria) this;
        }

        public Criteria andFavoritesIdBetween(Long value1, Long value2) {
            addCriterion("favorites_id between", value1, value2, "favoritesId");
            return (Criteria) this;
        }

        public Criteria andFavoritesIdNotBetween(Long value1, Long value2) {
            addCriterion("favorites_id not between", value1, value2, "favoritesId");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yangmao_favorites
     *
     * @mbggenerated do_not_delete_during_merge Fri Aug 26 17:19:12 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yangmao_favorites
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}