package com.yangmao.dal.dataobj;

import java.util.Date;

public class YangmaoClick {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_click.click_id
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    private Long clickId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_click.email
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_click.mail_instance_id
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    private Long mailInstanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_click.item_id
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_click.create_time
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_click.click_id
     *
     * @return the value of yangmao_click.click_id
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public Long getClickId() {
        return clickId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_click.click_id
     *
     * @param clickId the value for yangmao_click.click_id
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public void setClickId(Long clickId) {
        this.clickId = clickId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_click.email
     *
     * @return the value of yangmao_click.email
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_click.email
     *
     * @param email the value for yangmao_click.email
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_click.mail_instance_id
     *
     * @return the value of yangmao_click.mail_instance_id
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public Long getMailInstanceId() {
        return mailInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_click.mail_instance_id
     *
     * @param mailInstanceId the value for yangmao_click.mail_instance_id
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public void setMailInstanceId(Long mailInstanceId) {
        this.mailInstanceId = mailInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_click.item_id
     *
     * @return the value of yangmao_click.item_id
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_click.item_id
     *
     * @param itemId the value for yangmao_click.item_id
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_click.create_time
     *
     * @return the value of yangmao_click.create_time
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_click.create_time
     *
     * @param createTime the value for yangmao_click.create_time
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}