package com.yangmao.dal.dataobj;

public class YangmaoTemplateSection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_template_section.section_id
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    private Long sectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_template_section.template_id
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    private Long templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_template_section.favorites_id
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    private Long favoritesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_template_section.section
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    private String section;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_template_section.section_amount
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    private Integer sectionAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_template_section.section_id
     *
     * @return the value of yangmao_template_section.section_id
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public Long getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_template_section.section_id
     *
     * @param sectionId the value for yangmao_template_section.section_id
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public void setSectionId(Long sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_template_section.template_id
     *
     * @return the value of yangmao_template_section.template_id
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public Long getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_template_section.template_id
     *
     * @param templateId the value for yangmao_template_section.template_id
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_template_section.favorites_id
     *
     * @return the value of yangmao_template_section.favorites_id
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public Long getFavoritesId() {
        return favoritesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_template_section.favorites_id
     *
     * @param favoritesId the value for yangmao_template_section.favorites_id
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public void setFavoritesId(Long favoritesId) {
        this.favoritesId = favoritesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_template_section.section
     *
     * @return the value of yangmao_template_section.section
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public String getSection() {
        return section;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_template_section.section
     *
     * @param section the value for yangmao_template_section.section
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public void setSection(String section) {
        this.section = section == null ? null : section.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_template_section.section_amount
     *
     * @return the value of yangmao_template_section.section_amount
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public Integer getSectionAmount() {
        return sectionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_template_section.section_amount
     *
     * @param sectionAmount the value for yangmao_template_section.section_amount
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public void setSectionAmount(Integer sectionAmount) {
        this.sectionAmount = sectionAmount;
    }
}