package com.yangmao.dal.dataobj;

import java.util.Date;

public class YangmaoMailInstance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_mail_instance.mail_instance_id
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    private Long mailInstanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_mail_instance.template_id
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    private Long templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_mail_instance.title
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_mail_instance.status
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_mail_instance.expire_time
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_mail_instance.create_time
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_mail_instance.last_update_time
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yangmao_mail_instance.content
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_mail_instance.mail_instance_id
     *
     * @return the value of yangmao_mail_instance.mail_instance_id
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    public Long getMailInstanceId() {
        return mailInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_mail_instance.mail_instance_id
     *
     * @param mailInstanceId the value for yangmao_mail_instance.mail_instance_id
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    public void setMailInstanceId(Long mailInstanceId) {
        this.mailInstanceId = mailInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_mail_instance.template_id
     *
     * @return the value of yangmao_mail_instance.template_id
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    public Long getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_mail_instance.template_id
     *
     * @param templateId the value for yangmao_mail_instance.template_id
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_mail_instance.title
     *
     * @return the value of yangmao_mail_instance.title
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_mail_instance.title
     *
     * @param title the value for yangmao_mail_instance.title
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_mail_instance.status
     *
     * @return the value of yangmao_mail_instance.status
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_mail_instance.status
     *
     * @param status the value for yangmao_mail_instance.status
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_mail_instance.expire_time
     *
     * @return the value of yangmao_mail_instance.expire_time
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_mail_instance.expire_time
     *
     * @param expireTime the value for yangmao_mail_instance.expire_time
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_mail_instance.create_time
     *
     * @return the value of yangmao_mail_instance.create_time
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_mail_instance.create_time
     *
     * @param createTime the value for yangmao_mail_instance.create_time
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_mail_instance.last_update_time
     *
     * @return the value of yangmao_mail_instance.last_update_time
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_mail_instance.last_update_time
     *
     * @param lastUpdateTime the value for yangmao_mail_instance.last_update_time
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yangmao_mail_instance.content
     *
     * @return the value of yangmao_mail_instance.content
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yangmao_mail_instance.content
     *
     * @param content the value for yangmao_mail_instance.content
     *
     * @mbggenerated Mon Aug 29 18:23:32 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}