package com.yangmao.dal.dataobj;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class YangmaoReplaceFieldExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public YangmaoReplaceFieldExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andReplaceFieldIdIsNull() {
            addCriterion("replace_field_id is null");
            return (Criteria) this;
        }

        public Criteria andReplaceFieldIdIsNotNull() {
            addCriterion("replace_field_id is not null");
            return (Criteria) this;
        }

        public Criteria andReplaceFieldIdEqualTo(Long value) {
            addCriterion("replace_field_id =", value, "replaceFieldId");
            return (Criteria) this;
        }

        public Criteria andReplaceFieldIdNotEqualTo(Long value) {
            addCriterion("replace_field_id <>", value, "replaceFieldId");
            return (Criteria) this;
        }

        public Criteria andReplaceFieldIdGreaterThan(Long value) {
            addCriterion("replace_field_id >", value, "replaceFieldId");
            return (Criteria) this;
        }

        public Criteria andReplaceFieldIdGreaterThanOrEqualTo(Long value) {
            addCriterion("replace_field_id >=", value, "replaceFieldId");
            return (Criteria) this;
        }

        public Criteria andReplaceFieldIdLessThan(Long value) {
            addCriterion("replace_field_id <", value, "replaceFieldId");
            return (Criteria) this;
        }

        public Criteria andReplaceFieldIdLessThanOrEqualTo(Long value) {
            addCriterion("replace_field_id <=", value, "replaceFieldId");
            return (Criteria) this;
        }

        public Criteria andReplaceFieldIdIn(List<Long> values) {
            addCriterion("replace_field_id in", values, "replaceFieldId");
            return (Criteria) this;
        }

        public Criteria andReplaceFieldIdNotIn(List<Long> values) {
            addCriterion("replace_field_id not in", values, "replaceFieldId");
            return (Criteria) this;
        }

        public Criteria andReplaceFieldIdBetween(Long value1, Long value2) {
            addCriterion("replace_field_id between", value1, value2, "replaceFieldId");
            return (Criteria) this;
        }

        public Criteria andReplaceFieldIdNotBetween(Long value1, Long value2) {
            addCriterion("replace_field_id not between", value1, value2, "replaceFieldId");
            return (Criteria) this;
        }

        public Criteria andTemplateReplaceNameIsNull() {
            addCriterion("template_replace_name is null");
            return (Criteria) this;
        }

        public Criteria andTemplateReplaceNameIsNotNull() {
            addCriterion("template_replace_name is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateReplaceNameEqualTo(String value) {
            addCriterion("template_replace_name =", value, "templateReplaceName");
            return (Criteria) this;
        }

        public Criteria andTemplateReplaceNameNotEqualTo(String value) {
            addCriterion("template_replace_name <>", value, "templateReplaceName");
            return (Criteria) this;
        }

        public Criteria andTemplateReplaceNameGreaterThan(String value) {
            addCriterion("template_replace_name >", value, "templateReplaceName");
            return (Criteria) this;
        }

        public Criteria andTemplateReplaceNameGreaterThanOrEqualTo(String value) {
            addCriterion("template_replace_name >=", value, "templateReplaceName");
            return (Criteria) this;
        }

        public Criteria andTemplateReplaceNameLessThan(String value) {
            addCriterion("template_replace_name <", value, "templateReplaceName");
            return (Criteria) this;
        }

        public Criteria andTemplateReplaceNameLessThanOrEqualTo(String value) {
            addCriterion("template_replace_name <=", value, "templateReplaceName");
            return (Criteria) this;
        }

        public Criteria andTemplateReplaceNameLike(String value) {
            addCriterion("template_replace_name like", value, "templateReplaceName");
            return (Criteria) this;
        }

        public Criteria andTemplateReplaceNameNotLike(String value) {
            addCriterion("template_replace_name not like", value, "templateReplaceName");
            return (Criteria) this;
        }

        public Criteria andTemplateReplaceNameIn(List<String> values) {
            addCriterion("template_replace_name in", values, "templateReplaceName");
            return (Criteria) this;
        }

        public Criteria andTemplateReplaceNameNotIn(List<String> values) {
            addCriterion("template_replace_name not in", values, "templateReplaceName");
            return (Criteria) this;
        }

        public Criteria andTemplateReplaceNameBetween(String value1, String value2) {
            addCriterion("template_replace_name between", value1, value2, "templateReplaceName");
            return (Criteria) this;
        }

        public Criteria andTemplateReplaceNameNotBetween(String value1, String value2) {
            addCriterion("template_replace_name not between", value1, value2, "templateReplaceName");
            return (Criteria) this;
        }

        public Criteria andDatabaseFieldIsNull() {
            addCriterion("database_field is null");
            return (Criteria) this;
        }

        public Criteria andDatabaseFieldIsNotNull() {
            addCriterion("database_field is not null");
            return (Criteria) this;
        }

        public Criteria andDatabaseFieldEqualTo(String value) {
            addCriterion("database_field =", value, "databaseField");
            return (Criteria) this;
        }

        public Criteria andDatabaseFieldNotEqualTo(String value) {
            addCriterion("database_field <>", value, "databaseField");
            return (Criteria) this;
        }

        public Criteria andDatabaseFieldGreaterThan(String value) {
            addCriterion("database_field >", value, "databaseField");
            return (Criteria) this;
        }

        public Criteria andDatabaseFieldGreaterThanOrEqualTo(String value) {
            addCriterion("database_field >=", value, "databaseField");
            return (Criteria) this;
        }

        public Criteria andDatabaseFieldLessThan(String value) {
            addCriterion("database_field <", value, "databaseField");
            return (Criteria) this;
        }

        public Criteria andDatabaseFieldLessThanOrEqualTo(String value) {
            addCriterion("database_field <=", value, "databaseField");
            return (Criteria) this;
        }

        public Criteria andDatabaseFieldLike(String value) {
            addCriterion("database_field like", value, "databaseField");
            return (Criteria) this;
        }

        public Criteria andDatabaseFieldNotLike(String value) {
            addCriterion("database_field not like", value, "databaseField");
            return (Criteria) this;
        }

        public Criteria andDatabaseFieldIn(List<String> values) {
            addCriterion("database_field in", values, "databaseField");
            return (Criteria) this;
        }

        public Criteria andDatabaseFieldNotIn(List<String> values) {
            addCriterion("database_field not in", values, "databaseField");
            return (Criteria) this;
        }

        public Criteria andDatabaseFieldBetween(String value1, String value2) {
            addCriterion("database_field between", value1, value2, "databaseField");
            return (Criteria) this;
        }

        public Criteria andDatabaseFieldNotBetween(String value1, String value2) {
            addCriterion("database_field not between", value1, value2, "databaseField");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Byte value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Byte value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Byte value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Byte value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Byte value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Byte value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Byte> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Byte> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Byte value1, Byte value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Byte value1, Byte value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 14 10:55:31 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}