package com.yangmao.dal.dao;

import com.yangmao.dal.dataobj.YangmaoEmailGettingHistory;
import com.yangmao.dal.dataobj.YangmaoEmailGettingHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YangmaoEmailGettingHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_getting_history
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    int countByExample(YangmaoEmailGettingHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_getting_history
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    int deleteByExample(YangmaoEmailGettingHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_getting_history
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    int deleteByPrimaryKey(Long historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_getting_history
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    int insert(YangmaoEmailGettingHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_getting_history
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    int insertSelective(YangmaoEmailGettingHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_getting_history
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    List<YangmaoEmailGettingHistory> selectByExample(YangmaoEmailGettingHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_getting_history
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    YangmaoEmailGettingHistory selectByPrimaryKey(Long historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_getting_history
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") YangmaoEmailGettingHistory record, @Param("example") YangmaoEmailGettingHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_getting_history
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    int updateByExample(@Param("record") YangmaoEmailGettingHistory record, @Param("example") YangmaoEmailGettingHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_getting_history
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    int updateByPrimaryKeySelective(YangmaoEmailGettingHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_getting_history
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    int updateByPrimaryKey(YangmaoEmailGettingHistory record);
}