package com.yangmao.dal.dao;

import com.yangmao.dal.dataobj.YangmaoClick;
import com.yangmao.dal.dataobj.YangmaoClickExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YangmaoClickMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    int countByExample(YangmaoClickExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    int deleteByExample(YangmaoClickExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    int deleteByPrimaryKey(Long clickId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    int insert(YangmaoClick record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    int insertSelective(YangmaoClick record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    List<YangmaoClick> selectByExample(YangmaoClickExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    YangmaoClick selectByPrimaryKey(Long clickId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") YangmaoClick record, @Param("example") YangmaoClickExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    int updateByExample(@Param("record") YangmaoClick record, @Param("example") YangmaoClickExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    int updateByPrimaryKeySelective(YangmaoClick record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_click
     *
     * @mbggenerated Mon Aug 29 11:14:14 CST 2016
     */
    int updateByPrimaryKey(YangmaoClick record);
}