package com.yangmao.dal.dao;

import com.yangmao.dal.dataobj.YangmaoMailTemplate;
import com.yangmao.dal.dataobj.YangmaoMailTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YangmaoMailTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_mail_template
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int countByExample(YangmaoMailTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_mail_template
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int deleteByExample(YangmaoMailTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_mail_template
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int deleteByPrimaryKey(Long templateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_mail_template
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int insert(YangmaoMailTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_mail_template
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int insertSelective(YangmaoMailTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_mail_template
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    List<YangmaoMailTemplate> selectByExampleWithBLOBs(YangmaoMailTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_mail_template
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    List<YangmaoMailTemplate> selectByExample(YangmaoMailTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_mail_template
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    YangmaoMailTemplate selectByPrimaryKey(Long templateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_mail_template
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") YangmaoMailTemplate record, @Param("example") YangmaoMailTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_mail_template
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") YangmaoMailTemplate record, @Param("example") YangmaoMailTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_mail_template
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int updateByExample(@Param("record") YangmaoMailTemplate record, @Param("example") YangmaoMailTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_mail_template
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int updateByPrimaryKeySelective(YangmaoMailTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_mail_template
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(YangmaoMailTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_mail_template
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int updateByPrimaryKey(YangmaoMailTemplate record);
}