package com.yangmao.dal.dao;

import com.yangmao.dal.dataobj.YangmaoEmailSender;
import com.yangmao.dal.dataobj.YangmaoEmailSenderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YangmaoEmailSenderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_sender
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int countByExample(YangmaoEmailSenderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_sender
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int deleteByExample(YangmaoEmailSenderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_sender
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int deleteByPrimaryKey(Long senderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_sender
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int insert(YangmaoEmailSender record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_sender
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int insertSelective(YangmaoEmailSender record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_sender
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    List<YangmaoEmailSender> selectByExample(YangmaoEmailSenderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_sender
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    YangmaoEmailSender selectByPrimaryKey(Long senderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_sender
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") YangmaoEmailSender record, @Param("example") YangmaoEmailSenderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_sender
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int updateByExample(@Param("record") YangmaoEmailSender record, @Param("example") YangmaoEmailSenderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_sender
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int updateByPrimaryKeySelective(YangmaoEmailSender record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_email_sender
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int updateByPrimaryKey(YangmaoEmailSender record);
}