package com.yangmao.dal.dao;

import com.yangmao.dal.dataobj.YangmaoFavoritesItem;
import com.yangmao.dal.dataobj.YangmaoFavoritesItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YangmaoFavoritesItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites_item
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int countByExample(YangmaoFavoritesItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites_item
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int deleteByExample(YangmaoFavoritesItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites_item
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int deleteByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites_item
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int insert(YangmaoFavoritesItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites_item
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int insertSelective(YangmaoFavoritesItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites_item
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    List<YangmaoFavoritesItem> selectByExample(YangmaoFavoritesItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites_item
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    YangmaoFavoritesItem selectByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites_item
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") YangmaoFavoritesItem record, @Param("example") YangmaoFavoritesItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites_item
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int updateByExample(@Param("record") YangmaoFavoritesItem record, @Param("example") YangmaoFavoritesItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites_item
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int updateByPrimaryKeySelective(YangmaoFavoritesItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_favorites_item
     *
     * @mbggenerated Fri Aug 26 17:19:12 CST 2016
     */
    int updateByPrimaryKey(YangmaoFavoritesItem record);
}