package com.yangmao.dal.dao;

import com.yangmao.dal.dataobj.YangmaoReplaceField;
import com.yangmao.dal.dataobj.YangmaoReplaceFieldExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YangmaoReplaceFieldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    int countByExample(YangmaoReplaceFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    int deleteByExample(YangmaoReplaceFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    int deleteByPrimaryKey(Long replaceFieldId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    int insert(YangmaoReplaceField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    int insertSelective(YangmaoReplaceField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    List<YangmaoReplaceField> selectByExample(YangmaoReplaceFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    YangmaoReplaceField selectByPrimaryKey(Long replaceFieldId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") YangmaoReplaceField record, @Param("example") YangmaoReplaceFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    int updateByExample(@Param("record") YangmaoReplaceField record, @Param("example") YangmaoReplaceFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    int updateByPrimaryKeySelective(YangmaoReplaceField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yangmao_replace_field
     *
     * @mbggenerated Wed Sep 14 10:55:31 CST 2016
     */
    int updateByPrimaryKey(YangmaoReplaceField record);
}